services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: [ "make", "run" ]
    env_file:
      - .env
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/github.com/cockscomb/tinyurl
