// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/cockscomb/tinyurl/web"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*web.Server, error) {
	config, err := ParseEnv()
	if err != nil {
		return nil, err
	}
	serverConfig := &config.ServerConfig
	awsConfig := &config.AWSConfig
	config2, err := LoadAWSConfig(ctx, awsConfig)
	if err != nil {
		return nil, err
	}
	dynamoDBConfig := &config.DynamoDBConfig
	client := NewDynamoDBClient(config2, dynamoDBConfig)
	server := web.NewServer(serverConfig, client)
	return server, nil
}
