// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cockscomb/tinyurl/web"
)

// Injectors from wire.go:

func InitializeServer() (*web.Server, error) {
	config, err := ParseEnv()
	if err != nil {
		return nil, err
	}
	serverConfig := &config.ServerConfig
	server := web.NewServer(serverConfig)
	return server, nil
}
